### ISSUE TITLE
kernel crashes

### ISSUE THREAD

**Issue by amryounis** [targodan/jupyter-swi-prolog#12]
Traceback (most recent call last):
  File "G:\Python3105\lib\site-packages\tornado\web.py", line 1713, in _execute
    result = await result
  File "G:\Python3105\lib\asyncio\tasks.py", line 304, in __wakeup
    future.result()
  File "G:\Python3105\lib\site-packages\tornado\gen.py", line 776, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "G:\Python3105\lib\site-packages\notebook\services\sessions\handlers.py", line 74, in post
    model = yield maybe_future(
  File "G:\Python3105\lib\site-packages\tornado\gen.py", line 769, in run
    value = future.result()
  File "G:\Python3105\lib\site-packages\tornado\gen.py", line 776, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "G:\Python3105\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "G:\Python3105\lib\site-packages\tornado\gen.py", line 769, in run
    value = future.result()
  File "G:\Python3105\lib\site-packages\tornado\gen.py", line 776, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "G:\Python3105\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 110, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "G:\Python3105\lib\site-packages\tornado\gen.py", line 769, in run
    value = future.result()
  File "G:\Python3105\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "G:\Python3105\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "G:\Python3105\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "G:\Python3105\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "G:\Python3105\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "G:\Python3105\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "G:\Python3105\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "G:\Python3105\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "G:\Python3105\lib\site-packages\jupyter_client\multikernelmanager.py", line 214, in _async_start_kernel
    starter = ensure_async(km.start_kernel(**kwargs))
  File "G:\Python3105\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "G:\Python3105\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "G:\Python3105\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "G:\Python3105\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "G:\Python3105\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "G:\Python3105\lib\site-packages\jupyter_client\manager.py", line 83, in wrapper
    raise e
  File "G:\Python3105\lib\site-packages\jupyter_client\manager.py", line 75, in wrapper
    out = await method(self, *args, **kwargs)
  File "G:\Python3105\lib\site-packages\jupyter_client\manager.py", line 389, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "G:\Python3105\lib\site-packages\jupyter_client\utils.py", line 30, in wrapped
    raise e
  File "G:\Python3105\lib\site-packages\jupyter_client\utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "G:\Python3105\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "G:\Python3105\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "G:\Python3105\lib\asyncio\tasks.py", line 232, in __step
    result = coro.send(None)
  File "G:\Python3105\lib\site-packages\jupyter_client\manager.py", line 307, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "G:\Python3105\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 204, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "G:\Python3105\lib\site-packages\jupyter_client\launcher.py", line 170, in launch_kernel
    raise ex
  File "G:\Python3105\lib\site-packages\jupyter_client\launcher.py", line 158, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "G:\Python3105\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "G:\Python3105\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by xt0r3** [comment]
It could be because [PySwip](https://github.com/yuce/pyswip) on Ubuntu 18.04 or 20.04 only supports up to Prolog 7.6.4.
There may be some other conflict with Windows if your Prolog is too new
You should try to install version 7.6.4 and see if it helps
